### ISSUE TITLE
Intermittent Errors - ironkatz module

### ISSUE THREAD

**Issue by n8zwn** [m8r0wn/ActiveReign#3]
Here is some errors that I have seen when running ironkatz, it is worth noting that in the for loop that these errors did not stop it from going on to the next host:

The command as I was running it:

```activereign enum -u user -p password --local-auth -M ironkatz $ip```

I also ran it in a for loop because when I fed it the target file with 930 IPs, it got stuck and never finished. 

```Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/ops/enum/code_execution.py", line 10, in execute
    self.result = self.exec_obj.execute(self.command)
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 61, in execute
    self.create_wmi_con()
  File "/home/user/.local/lib/python3.6/site-packages/ar3/core/wmiexec.py", line 53, in create_wmi_con
    iInterface = self.dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1057, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1836, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 856, in request
    answer = self.recv()
  File "/home/user/.local/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied```

**Comment by n8zwn** [comment]
I thought I should mention that the credentials are valid and if I run the psexec module in metasploit, then execute mimikatz that I don't see any errors, which then pulls the clear text creds. These errors happen in the mimikatz module as well.

**Comment by m8r0wn** [comment]
Hi @n8zwn,

Often times I have found the issue with the mimikatz/ironkatz payloads is the timeout. The payload is not given enough time to download & execute before the results are checked by AR3. However, I would expect the error to be returned in PowerShell not the Python code (specifically in the Impacket library).

What OS is this running against and do you see the "Adm!n" tag? If this is a newer OS, such as Windows 10, UAC may be blocking this access.

What version of Impacket are you using as well?
```pip3 freeze|grep impacket```

For example, I am using a Kali Linux OS with:
![Screen Shot 2019-09-26 at 8 57 38 AM](https://user-images.githubusercontent.com/13889819/65690194-82491d00-e03c-11e9-9c1b-657ee6207a12.png)

I have just tested both the ironkatz and mimikatz payloads successfully on a Windows 2012r2, but still working on compatibility with more OS versions. *(Was debating releasing a compatibility worksheet outlining AR3 features and OS version they have been tested against)*

**Comment by n8zwn** [comment]
<img width="325" alt="Screen Shot 2019-09-26 at 9 48 49 AM" src="https://user-images.githubusercontent.com/6550058/65703943-deaf3b00-e042-11e9-9c3c-374fad0605c6.png">

**Comment by n8zwn** [comment]
I saw you are using 3.7 so I will do some additional testing. Can we set the timeout time before AR3 checks? Also, this is a great tool so I appreciate you being so responsive!

**Comment by n8zwn** [comment]
Looks like the error does not happen anymore after changing my version of python. Not getting anything back, but that could be due to the timeout. I know that at least a 30 second wait did not get the data back. I will close this out

**Comment by m8r0wn** [comment]
I'm glad the error has gone away! However, I agree, we will have to put in some more work to perfect the mimikatz/ironkatz modules.
