### ISSUE TITLE
no module called impacket

### ISSUE THREAD

**Issue by pretech86** [m8r0wn/ActiveReign#5]
activereign enum -u user01 -p 123 -d demo.local 192.168.8.1/24
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/ActiveReign-8Dj1w3E8/bin/activereign", line 11, in <module>
    load_entry_point('ActiveReign==1.0.5', 'console_scripts', 'activereign')()
  File "/root/.local/share/virtualenvs/ActiveReign-8Dj1w3E8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.local/share/virtualenvs/ActiveReign-8Dj1w3E8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/root/.local/share/virtualenvs/ActiveReign-8Dj1w3E8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/root/.local/share/virtualenvs/ActiveReign-8Dj1w3E8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.local/share/virtualenvs/ActiveReign-8Dj1w3E8/lib/python3.7/site-packages/ActiveReign-1.0.5-py3.7.egg/ar3/__init__.py", line 14, in <module>
  File "/root/.local/share/virtualenvs/ActiveReign-8Dj1w3E8/lib/python3.7/site-packages/ActiveReign-1.0.5-py3.7.egg/ar3/ops/enum/__init__.py", line 7, in <module>
  File "/root/.local/share/virtualenvs/ActiveReign-8Dj1w3E8/lib/python3.7/site-packages/ActiveReign-1.0.5-py3.7.egg/ar3/servers/smb.py", line 11, in <module>
ModuleNotFoundError: No module named 'impacket'

**Comment by m8r0wn** [comment]
Hi @pretech86,

Thanks for the heads up, just need a bit more info. How did you install ActiveReign? Did you use ```--recursive ``` during install? This will pull down all sub modules.
\-m8r0wn

**Comment by m8r0wn** [comment]
Not enough info, closing. Checkout the installation page in the wiki, and let me know if you have any more issues.

[https://github.com/m8r0wn/ActiveReign/wiki/Installation](https://github.com/m8r0wn/ActiveReign/wiki/Installation)

\-m8r0wn
